[package]
name = "project"
version = "0.1.0"
edition = "2018"

[dependencies]
ocl = "0.19"
bip39 = "1.0"
hex = "0.4"
rusqlite = { version = "0.26", features = ["bundled"] }

[[bin]]
name = "project"
path = "src/main.rs"
